version: "3.5"
services:
  selenium-hub:
    container_name: ${WARDEN_ENV_NAME}_selenium-hub
    hostname: selenium-hub
    image: selenium/hub:3.8.1
    networks:
      - warden
      - default
  selenium-chrome:
    hostname: ${WARDEN_ENV_NAME}_selenium-chrome
    image: selenium/node-chrome:3.8.1
    extra_hosts:
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=false
    networks:
      - warden
      - default
